---

- name: add new chocolatey internal source
  win_chocolatey_source:
    name: '{{ choco_ext_repo_name }}'
    state: present
    source: '{{ choco_ext_repo_source }}'

- name: install onec platform {{ v8version }} x64
  win_chocolatey:
    name: 1c
    version: '{{ v8version }}'
    force: yes
    allow_multiple: yes
  register: onec_server_install_result

- debug:
    var: onec_server_install_result

- name: install onec platform {{ v8version }} x86
  win_chocolatey:
    name: 1c
    version: '{{ v8version }}'
    architecture: 'x86'
    force: yes
    allow_multiple: yes
  register: onec_install_result

- debug:
    var: onec_install_result
