---
- name: deploy onec server
  hosts: test
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: create ansible temp directory
      win_file:
        path: "{{ ansible_win_temp_dir }}"
        state: directory
        ignore_errors: true
    #- name: uninstall previous platform
  roles:
    - role: onec-server
      v8version: "8.3.16.1148"

