---
- name: get keys haspip
  hosts: onecservers
  gather_facts: no
  
  tasks:

    - name: get hasp info
      win_uri:
        url: "http://localhost:1947/tab_dev.html"
        return_content: yes
      register: http_output

    - debug:
        var: http_output.content | regex_findall('(?:"haspid":")(.*?)(?:")')