---
- name: deploy onec on termserver
  hosts: test
  vars_files: 
    - secrets.yml
  pre_tasks:
    - name: create ansible temp directory
      win_file:
        path: "{{ ansible_win_temp_dir }}"
        state: directory
        ignore_errors: true
  roles:
    - role: onec-termserver
      v8version: "8.3.16.1148"
